/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "k8s.io/cluster-registry/pkg/apis/clusterregistry/v1alpha1"
)

// FakeClusterCredentialses implements ClusterCredentialsInterface
type FakeClusterCredentialses struct {
	Fake *FakeClusterregistryV1alpha1
	ns   string
}

var clustercredentialsesResource = schema.GroupVersionResource{Group: "clusterregistry.k8s.io", Version: "v1alpha1", Resource: "clustercredentialses"}

var clustercredentialsesKind = schema.GroupVersionKind{Group: "clusterregistry.k8s.io", Version: "v1alpha1", Kind: "ClusterCredentials"}

// Get takes name of the clusterCredentials, and returns the corresponding clusterCredentials object, and an error if there is any.
func (c *FakeClusterCredentialses) Get(name string, options v1.GetOptions) (result *v1alpha1.ClusterCredentials, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clustercredentialsesResource, c.ns, name), &v1alpha1.ClusterCredentials{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterCredentials), err
}

// List takes label and field selectors, and returns the list of ClusterCredentialses that match those selectors.
func (c *FakeClusterCredentialses) List(opts v1.ListOptions) (result *v1alpha1.ClusterCredentialsList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clustercredentialsesResource, clustercredentialsesKind, c.ns, opts), &v1alpha1.ClusterCredentialsList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterCredentialsList{ListMeta: obj.(*v1alpha1.ClusterCredentialsList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterCredentialsList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterCredentialses.
func (c *FakeClusterCredentialses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clustercredentialsesResource, c.ns, opts))

}

// Create takes the representation of a clusterCredentials and creates it.  Returns the server's representation of the clusterCredentials, and an error, if there is any.
func (c *FakeClusterCredentialses) Create(clusterCredentials *v1alpha1.ClusterCredentials) (result *v1alpha1.ClusterCredentials, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clustercredentialsesResource, c.ns, clusterCredentials), &v1alpha1.ClusterCredentials{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterCredentials), err
}

// Update takes the representation of a clusterCredentials and updates it. Returns the server's representation of the clusterCredentials, and an error, if there is any.
func (c *FakeClusterCredentialses) Update(clusterCredentials *v1alpha1.ClusterCredentials) (result *v1alpha1.ClusterCredentials, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clustercredentialsesResource, c.ns, clusterCredentials), &v1alpha1.ClusterCredentials{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterCredentials), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterCredentialses) UpdateStatus(clusterCredentials *v1alpha1.ClusterCredentials) (*v1alpha1.ClusterCredentials, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(clustercredentialsesResource, "status", c.ns, clusterCredentials), &v1alpha1.ClusterCredentials{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterCredentials), err
}

// Delete takes name of the clusterCredentials and deletes it. Returns an error if one occurs.
func (c *FakeClusterCredentialses) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(clustercredentialsesResource, c.ns, name), &v1alpha1.ClusterCredentials{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterCredentialses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(clustercredentialsesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterCredentialsList{})
	return err
}

// Patch applies the patch and returns the patched clusterCredentials.
func (c *FakeClusterCredentialses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterCredentials, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clustercredentialsesResource, c.ns, name, data, subresources...), &v1alpha1.ClusterCredentials{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterCredentials), err
}
