/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "k8s.io/cluster-registry/pkg/apis/clusterregistry/v1alpha1"
	scheme "k8s.io/cluster-registry/pkg/client/clientset/versioned/scheme"
)

// ClusterCredentialsesGetter has a method to return a ClusterCredentialsInterface.
// A group's client should implement this interface.
type ClusterCredentialsesGetter interface {
	ClusterCredentialses(namespace string) ClusterCredentialsInterface
}

// ClusterCredentialsInterface has methods to work with ClusterCredentials resources.
type ClusterCredentialsInterface interface {
	Create(*v1alpha1.ClusterCredentials) (*v1alpha1.ClusterCredentials, error)
	Update(*v1alpha1.ClusterCredentials) (*v1alpha1.ClusterCredentials, error)
	UpdateStatus(*v1alpha1.ClusterCredentials) (*v1alpha1.ClusterCredentials, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ClusterCredentials, error)
	List(opts v1.ListOptions) (*v1alpha1.ClusterCredentialsList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterCredentials, err error)
	ClusterCredentialsExpansion
}

// clusterCredentialses implements ClusterCredentialsInterface
type clusterCredentialses struct {
	client rest.Interface
	ns     string
}

// newClusterCredentialses returns a ClusterCredentialses
func newClusterCredentialses(c *ClusterregistryV1alpha1Client, namespace string) *clusterCredentialses {
	return &clusterCredentialses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the clusterCredentials, and returns the corresponding clusterCredentials object, and an error if there is any.
func (c *clusterCredentialses) Get(name string, options v1.GetOptions) (result *v1alpha1.ClusterCredentials, err error) {
	result = &v1alpha1.ClusterCredentials{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clustercredentialses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterCredentialses that match those selectors.
func (c *clusterCredentialses) List(opts v1.ListOptions) (result *v1alpha1.ClusterCredentialsList, err error) {
	result = &v1alpha1.ClusterCredentialsList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clustercredentialses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterCredentialses.
func (c *clusterCredentialses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("clustercredentialses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a clusterCredentials and creates it.  Returns the server's representation of the clusterCredentials, and an error, if there is any.
func (c *clusterCredentialses) Create(clusterCredentials *v1alpha1.ClusterCredentials) (result *v1alpha1.ClusterCredentials, err error) {
	result = &v1alpha1.ClusterCredentials{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("clustercredentialses").
		Body(clusterCredentials).
		Do().
		Into(result)
	return
}

// Update takes the representation of a clusterCredentials and updates it. Returns the server's representation of the clusterCredentials, and an error, if there is any.
func (c *clusterCredentialses) Update(clusterCredentials *v1alpha1.ClusterCredentials) (result *v1alpha1.ClusterCredentials, err error) {
	result = &v1alpha1.ClusterCredentials{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clustercredentialses").
		Name(clusterCredentials.Name).
		Body(clusterCredentials).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *clusterCredentialses) UpdateStatus(clusterCredentials *v1alpha1.ClusterCredentials) (result *v1alpha1.ClusterCredentials, err error) {
	result = &v1alpha1.ClusterCredentials{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clustercredentialses").
		Name(clusterCredentials.Name).
		SubResource("status").
		Body(clusterCredentials).
		Do().
		Into(result)
	return
}

// Delete takes name of the clusterCredentials and deletes it. Returns an error if one occurs.
func (c *clusterCredentialses) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clustercredentialses").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterCredentialses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clustercredentialses").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched clusterCredentials.
func (c *clusterCredentialses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterCredentials, err error) {
	result = &v1alpha1.ClusterCredentials{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("clustercredentialses").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
